### ISSUE TITLE
Support for Zeek

### ISSUE THREAD

**Issue by DigiAngel** [J-Gras/zeek-af_packet-plugin#14]
Can we please get this for Zeek?  By this I mean changing ALL things to zeek...no more "/opt/zeek/bin/zeek -NN Bro::AF_Packet"....having everything point to zeek.  Thank you.

**Comment by J-Gras** [comment]
I plan to do a complete renaming in the next weeks.

**Comment by DigiAngel** [comment]
Beautiful thank you!

**Comment by atkinsj** [comment]
Fwiw this is throwing dep warnings now:

`Warning: Plugin 'af_packet' uses deprecated method 'broctl_config'; use 'zeekctl_config' instead`

**Comment by J-Gras** [comment]
Thanks to Tim, everything should be renamed now.

**Comment by DigiAngel** [comment]
Thank you!
