### ISSUE TITLE
Crashing when using multiple interfaces

### ISSUE THREAD

**Issue by DigiAngel** [J-Gras/zeek-af_packet-plugin#16]
Maybe I'm using this wrong, but here goes:
~~~
[worker-1]
type=worker
host=localhost
interface=enp132s0
lb_method=custom
lb_procs=3
pin_cpus=0,1,12
#
[worker-2]
type=worker
host=localhost
interface=eno3
lb_method=custom
lb_procs=3
pin_cpus=2,3,14

[worker-3]
type=worker
host=localhost
interface=ens5
lb_method=custom
lb_procs=3
pin_cpus=8,9,20
~~~

I have lb_custom.InterfacePrefix=af_packet:: set, but for the life of me this crashes when I start with:
~~~
==== stderr.log
fatal error: problem with interface af_packet::ens5 (Invalid argument)
~~~

af_packet test:
~~~
Zeek::AF_Packet - Packet acquisition via AF_Packet (dynamic, version 2.0.0)
    [Packet Source] AF_PacketReader (interface prefix "af_packet"; supports live input)
    [Type] AF_Packet::FanoutMode
    [Constant] AF_Packet::buffer_size
    [Constant] AF_Packet::enable_hw_timestamping
    [Constant] AF_Packet::enable_fanout
    [Constant] AF_Packet::fanout_mode
    [Constant] AF_Packet::fanout_id
~~~

Not sure where to look for a fix...thank you.

**Comment by J-Gras** [comment]
In case we are tracing down a bug it would be important to know which version of zeek you are running and on which OS. However, the described issue might be a fanout_id collision. Please try adding `af_packet_fanout_id=42` to your `node.cfg` with **different** values for each worker. In case you run other monitoring software (e.g., Suricata) in parallel, make sure it is configured with distinct fanout IDs as well.

Some background on fanout IDs can be found in the [man pages](http://man7.org/linux/man-pages/man7/packet.7.html):
> To scale processing across threads, packet sockets can form a fanout group.  In this mode, each matching packet is enqueued onto only one socket in the group.  A socket joins a fanout group by calling setsockopt(2) with level SOL_PACKET and option PACKET_FANOUT.  Each network namespace can have up to 65536 independent groups.  A socket selects a group by encoding the ID in the first 16 bits of the integer option value. The first packet socket to join a group implicitly creates it. To successfully join an existing group, subsequent packet sockets must have the same protocol, device settings, fanout mode and flags (see below).  Packet sockets can leave a fanout group only by closing the socket.  The group is deleted when the last socket is closed.

**Comment by DigiAngel** [comment]
Thank you...that fixed it up with the fanout_id.  Falls inline also with that fact that the first worker was fine, but the other two were not.  Thanks again...this was 3.1.0 and Ubuntu 18 btw :)

**Comment by J-Gras** [comment]
You're welcome! I should probably add a note to the readme.
