### ISSUE TITLE
No support for fragmented IP packets

### ISSUE THREAD

**Issue by jojoob** [J-Gras/zeek-af_packet-plugin#17]
Zeek needs to process all packets of a flow by the same worker process. Without the AF_PACKET option PACKET_FANOUT_FLAG_DEFRAG the flow hash of fragmented packets is different ([PACKET(7) man](http://man7.org/linux/man-pages/man7/packet.7.html)). As a result packets belonging to the same flow may be processed by different worker processes.

I think the fix should be easy by adding this option when configuring the fanout group [here](https://github.com/J-Gras/zeek-af_packet-plugin/blob/master/src/AF_Packet.cc#L140).

**Comment by J-Gras** [comment]
The branch `defrag` introduces a new option `enable_defrag`, which is set to `F`. Unfortunately, I am too busy to test the changes right now. Feel free to give it a try. Keep in mind to enable defragmentation explicitly and let me know whether Zeek complains about checksums.

**Comment by jojoob** [comment]
I think the patch has a bug: The call to [ConfigureFanoutGroup](https://github.com/J-Gras/zeek-af_packet-plugin/blob/defrag/src/AF_Packet.cc#L65) must be changed as well to make it work:

```diff
diff --git a/src/AF_Packet.cc b/src/AF_Packet.cc
index fac0597..f4fa409 100644
--- a/src/AF_Packet.cc
+++ b/src/AF_Packet.cc
@@ -62,7 +62,7 @@ void AF_PacketSource::Open()
                return;
                }
 
-       if ( ! ConfigureFanoutGroup(enable_fanout) )
+       if ( ! ConfigureFanoutGroup(enable_fanout, enable_defrag) )
                {
                Error(errno ? strerror(errno) : "failed to join fanout group");
                close(socket_fd);
```

**Comment by J-Gras** [comment]
That was indeed an oversight. Thanks a lot for pointing that out! I fixed the branch. If that works for you, I am happy to merge this into master.

**Comment by J-Gras** [comment]
Added this to the 2.1.0 release.
