### ISSUE TITLE
Potential baseline update

### ISSUE THREAD

**Issue by dopheide-esnet** [J-Gras/zeek-af_packet-plugin#18]
Getting a baseline failure on zkg installation which seems to be the addition of enable_defrag on my system.  (It could be that that's something I need to disable and it's not an issue at all, pretty new to af_packet).  

  % 'btest-diff output' failed unexpectedly (exit code 1)
  % cat .diag
  == File ===============================
  Zeek::AF_Packet - Packet acquisition via AF_Packet (dynamic, version)
      [Packet Source] AF_PacketReader (interface prefix "af_packet"; supports live input)
      [Type] AF_Packet::FanoutMode
      [Constant] AF_Packet::buffer_size
      [Constant] AF_Packet::enable_hw_timestamping
      [Constant] AF_Packet::enable_fanout
      [Constant] AF_Packet::enable_defrag
      [Constant] AF_Packet::fanout_mode
      [Constant] AF_Packet::fanout_id

  == Diff ===============================
  --- /home/zeek/.zkg/testing/zeek-af_packet-plugin/clones/zeek-af_packet-plugin/tests/Baseline/scripts.show-plugin/output      2020-10-19 23:55:36.983946478 +0000
  +++ output    2020-10-19 23:55:47.077983027 +0000
  @@ -4,6 +4,7 @@
       [Constant] AF_Packet::buffer_size
       [Constant] AF_Packet::enable_hw_timestamping
       [Constant] AF_Packet::enable_fanout
  +    [Constant] AF_Packet::enable_defrag
       [Constant] AF_Packet::fanout_mode
       [Constant] AF_Packet::fanout_id

  =======================================

**Comment by J-Gras** [comment]
Fixed the baseline. Thanks a lot for reporting!
