### ISSUE TITLE
Detect when running in a container in FindKernelHeaders.cmake

### ISSUE THREAD

**Issue by dominiklohmann** [J-Gras/zeek-af_packet-plugin#29]
When building this plugin in a container, it must be built from source using CMake rather than using `zkg install` because `KERNELHEADERS_ROOT_DIR` must be specified manually. The find module `FindKernelHeaders.cmake` does not reliably work in containers because there might not be a  `linux-headers-$(uname -r)`.

Would you be willing to accept a patch that changes the find module to detect when running inside a container, setting `KERNELHEADERS_ROOT_DIR` to `/usr` automatically?

**Comment by J-Gras** [comment]
Building inside a container is indeed not well supported. This was also discussed in #24. Following this discussion zeek/package-manager#98 was opened, which would allow for a cleaner workflow using `zkg install`.

How reliable would the container detection be and would it be specific to e.g. docker? I also like Vlad's idea to fall back to `--with-latest-kernel` when no header is found.

**Comment by dominiklohmann** [comment]
I think Vlad''s idea works as well.

I usually use `[[ -f /.dockerenv ]] || grep -Eq '(lxc|docker)' /proc/1/cgroup` which detects both Docker and LXC reliably. There is no guarantee this won't break in the future, but adding such a check as a fallback to the find module can't do too much harm I think.

**Comment by J-Gras** [comment]
Turns out we can drop the kernel header dependency completely. Thus, the plugin should now build seamlessly in containers using `zkg`.
