### ISSUE TITLE
Combine packets from multiple interfaces

### ISSUE THREAD

**Issue by tobim** [J-Gras/zeek-af_packet-plugin#32]
I'm wondering whether the plugin can be used to listen on multiple interfaces simultaneously.

The setup has 2 NICs, one gets only inbound packets and one the other one only outbound. I already tried `interface=af_packet::eno5,eno6` in my `node.cfg`, but that failed to start.

Is such a setup supported with this plugin?

**Comment by J-Gras** [comment]
Hi tobim, unfortunately I am not aware of any straightforward way to merge traffic from multiple interfaces using AF-Packet. There is the idea to use bonding to combine multiple interfaces and then capture on the bonded interface, but I am not aware of any successful implementation. However, the recently released [DPDK plugin](https://github.com/esnet/dpdk-plugin) might allow to implement this.
