### ISSUE TITLE
Undefined symbol

### ISSUE THREAD

**Issue by Veshialle** [J-Gras/zeek-af_packet-plugin#35]
Trying to install both with zkg and directly from source it provide me error loading the libraries:
```
zeek -NN Zeek::AF_Packet
error in /opt/zeek/share/zeek/base/init-bare.zeek, line 1: cannot load plugin library /opt/zeek/lib/zeek/plugins/Zeek_AF_Packet//lib/Zeek-AF_Packet.linux-x86_64.so: /opt/zeek/lib/zeek/plugins/Zeek_AF_Packet//lib/Zeek-AF_Packet.linux-x86_64.so: undefined symbol: _ZN4zeek4util6detail10extract_ipERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
fatal error in /opt/zeek/share/zeek/base/init-bare.zeek, line 1: aborting after plugin errors
```

Here is the `./configure` output:
```./configure
Build Directory        : build
Zeek Source Directory   :
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test cxx17_already_works
-- Performing Test cxx17_already_works - Failed
-- Performing Test cxx17_works
-- Performing Test cxx17_works - Success
-- Found BinPAC: /opt/zeek/bin/binpac
-- Found CAF: 0.18.0  found components: core io openssl
-- Found Broker: /opt/zeek/lib/libbroker.a
-- Zeek executable      : /opt/zeek/bin/zeek
-- Zeek source          :
-- Zeek build           :
-- Zeek install prefix  : /opt/zeek
-- Zeek plugin directory: /opt/zeek/lib/zeek/plugins
-- Zeek debug mode      :
-- Found KernelHeaders: /usr/src/kernels/4.18.0-372.19.1.el8_6.x86_64
-- Kernelheader prefix : /usr/src/kernels/4.18.0-372.19.1.el8_6.x86_64
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/temp/zeek-af_packet-plugin-3.0.2/build
```

Zeek version from compiled binaries:
`zeek version 4.0.8`

Thanks!

**Comment by J-Gras** [comment]
The configure output looks good. Can you provide the output of the following commands:
```
zeek-config --zeek_dist
zeek-config --prefix
zeek-config --plugin_dir
zeek-config --include_dir
zkg config
```

**Comment by Veshialle** [comment]
Sure:
```
$ zeek-config --zeek_dist
#NO OUTPUT
$ zeek-config --prefix
/opt/zeek
$ zeek-config --plugin_dir
/opt/zeek/lib/zeek/plugins
$ zeek-config --include_dir
/opt/zeek/include:/opt/zeek/include/zeek:/usr/include:/usr/include:/usr/include:/usr/include:
$ zkg config
[sources]
zeek = https://github.com/zeek/packages

[paths]
state_dir = /root/.zkg
script_dir = /opt/zeek/share/zeek/site
plugin_dir = /opt/zeek/lib/zeek/plugins
zeek_dist =
```

**Comment by J-Gras** [comment]
That looks good as well. How did you install Zeek? Did you do any updates on Zeek?

**Comment by J-Gras** [comment]
Although the configured paths look okay, there might be some issues with leftovers from the previous installs. I suggest to remove all Zeek binary packages, then delete all files that might be left (including plugin related ones) and finally do a fresh install of Zeek and the plugin.

**Comment by Veshialle** [comment]
Made a new machine with Rocky Linux (8) (fresh new installation).
Installed binaries for zeek-lts, developer tools and still the same issue.

**Comment by J-Gras** [comment]
I will try to reproduce this. Might take some time...

**Comment by J-Gras** [comment]
As far as I can tell, the official repos don't support Rocky Linux. I gave the [CentOS_8_Stream](https://build.opensuse.org/package/binaries/security:zeek/zeek-lts/CentOS_8_Stream) repo a try but there are no packages available. Seems the build recently failed. However, as Rocky is not officially supported, I guess the recommended way would be to build Zeek from source. Doing so I am unable to reproduce the issue:

```
[root@Rocky8VM zeek-af_packet-plugin]# zeek -v
zeek version 4.0.8
[root@Rocky8VM zeek-af_packet-plugin]# zeek -NN Zeek::AF_Packet
Zeek::AF_Packet - Packet acquisition via AF_Packet (dynamic, version 3.2.0)
    [Packet Source] AF_PacketReader (interface prefix "af_packet"; supports live input)
    [Type] AF_Packet::FanoutMode
    [Constant] AF_Packet::buffer_size
    [Constant] AF_Packet::enable_hw_timestamping
    [Constant] AF_Packet::enable_fanout
    [Constant] AF_Packet::enable_defrag
    [Constant] AF_Packet::fanout_mode
    [Constant] AF_Packet::fanout_id
    [Constant] AF_Packet::link_type
```

Which repos did you use and which packages did you install?

**Comment by zipzoop11** [comment]
For Rocky I used the official Zeek LTS repo for CentOS7. Zeek seems to work, however the AF_PACKET throws the error described in this thread.

To get the latest Zeek 5.0.2 I had to compile from source, like you say. With Zeek compiled from source as you did, the error is not present and the plugin works as expected.

**Comment by J-Gras** [comment]
Although this might be unfortunate, I would not consider Zeek packaged for *CentOS 7* not working as expected on *Rocky Linux 8* a bug. I guess @0xxon might know what would be a suitable alternative.

**Comment by zipzoop11** [comment]
> Thanks a lot for chiming in, Oxxon! Given that this is a packaging issue for Zeek, I will close this issue. I hope building Zeek form source is a reasonable workaround for now.

It is. It seems to be the only way to get this plugin to work on anything past CentOS7. 
Building from source is not unreasonable.
